<?xml version="1.0"?>
<?xml-model 
  href="http://download.ros.org/schema/package_format3.xsd" 
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>examples_rclrs_action_demo</name>
  <maintainer email="nicolas.daube@botronics.be">Nicolas Daube</maintainer>
  <version>0.0.0</version>
  <description>Package containing an example of how to use actions in rclrs.</description>
  <license>Apache License 2.0</license>

  <depend>rclrs</depend>
  <depend>rosidl_runtime_rs</depend>
  <depend>example_interfaces</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>
